NOTE : 
- JIKA INGIN RECODE JANGAN LUPA LETAK CREDIT GUA " RIZZPIW "
- DILARANG JUAL SC INI DI BAWAH 5K
- DILARANG SHARE SC INI SECARA GRATIS/FREE

- © RIZZPIW
- BASE : RIZZPIW
- Wa.me/62895614033342 [ WA 1 ]
- Wa.me/6281268935404 [ WA 2 ]

- KETAHUAN JUAL SC INI DI BAWAH 5K DAN DI SEBAR LANGSUNG GUA FULL ENC! 

--------------------------------------------------------------------------------------------------------------------------------------------------------

- CARA MENJALANKAN SC INI

1. LOGIN KE AKUN PANEL KALIAN
2. MASUKIN USERNAME DAN PASSWORD PANEL KALIAN
3. JIKA SUDAH MASUK, KLIK NAMA PANEL KALIAN
4. JIKA SUDAH DI KLIK KELIAN KE FILE TERUS UPLOAD SC NYA
5. JIKA SUDAH DI UPLOAD KALIAN UNARCHIVE DAN KALIAN MOVE
6. JIKA SUDAH DI MOVE KALIAN KE STARTUP GANTI KE npm i 
7. JIKA SUDAH KE GANTI MENJADI npm i KALIAN KE CONSOLE TERUS KLIK START
8. JIKA MODULE NYA SUDAH KE INSTALL KALIAN KE STARTUP LAGI DAN GANTI KE npm start
9. JIKA SUDAH EK GANTI MENJADI npm start KALIAN KE CONSOLE LAGI DAN TUNGGU SAMPAI QR NYA MUNCUL


npm i = Unntuk Install Module
npm start = Untuk Menjalankan Bot

--------------------------------------------------------------------------------------------------------------------------------------------------------

- CARA GANTI FOTO 

- INGIN MENGGANTI FOTO PADA QRIS DANA,QRIS GOPAY,QRIS ALLPAY, DAN FOTO LOGO? CARA NYA CUKUP GAMPANG KALIAN SIAPIN AJA FOTO QRIS DANA,QRIS GOPAY,QRIS ALLPAY, DAN FOTO LOGO NYA TERUS KALIAN TEMPEL DI FOLDER IMAGE NAH KALIAN GANTI NAMA FOTO NYA MENJADI

QRIS DANA = dana.jpg
QRIS GOPAY = gopay.jpg
QRIS ALLPAY = qris.jpg
LOGO/THUMBNAIL = logo.jpg

MALES NGEDIT? BAWA DANA 5K AJA,CHAT KE NOMOR WA YANG ADA DI ATAS

--------------------------------------------------------------------------------------------------------------------------------------------------------

- KESALAHAN DALAM RECODE/RENAME/EDIT BUKAN SALAH GUA [ RIZZPIW ] DAN GUA [ RIZZPIW ] TIDAK AKAN MENGIRIM SC NYA 2× JADI JANGAN SAMPAI SALAH RECODE/RENAME/EDIT 

"- ALL TRX NO REFF"
"- MAKSA REFF? BLOK"